### PR TITLE
updating readme and minor cleanups

### PR DESCRIPTION
**Pull request by karalets**
Editing the readme slightly to make the instructions actually installable on a fresh environment.

More issues I saw here that require an update:

In the readme the command 

```conda install rdkit```
does currently not work, fails with
```
PackagesNotFoundError: The following packages are not available from current channels:
  - rdkit
```

Another issue I am mindful of:
int he requirements.txt we are not specifying versions of dependencies, which is not a good idea in general.

I'd like us to transition to specific versions and to maintain a version of pinot as well.
Can we add those changes in this PR and discuss them before I merge this?

Thanks guys.

### CODE REVIEW

**Comment by miretchin** [comment]
re: installing rdkit, we have to specify a channel, can't just do conda install rdkit.
```conda install -c conda-forge rdkit```
or
```conda install -c rdkit rdkit```

**Comment by karalets** [comment]
> re: installing rdkit, we have to specify a channel, can't just do conda install rdkit.
> `conda install -c conda-forge rdkit`
> or
> `conda install -c rdkit rdkit`
> 
> works instead

adding that as a change to the PR! thanks

**Comment by miretchin** [comment]
Another thing I noticed:

you can't do pip install -r requirements

pip expects an actual file:

```pip install -r requirements.txt```

**Comment by karalets** [comment]
> Another thing I noticed:
> 
> you can't do pip install -r requirements
> 
> pip expects an actual file:
> 
> `pip install -r requirements.txt`

that was already in this pr

**Pull request merged**
